[package]
name = "proof-conversion-utils"
version = "1.0.0"
edition = "2021"

[lib]
name = "pairing_utils"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "convert_from_sp1_groth16"
path = "src/bin/convert_from_sp1_groth16.rs"
required-features = ["sp1-bin"]

[[bin]]
name = "convert_from_snarkjs"
path = "src/bin/convert_from_snarkjs.rs"

[[bin]]
name = "alphabeta"
path = "src/bin/alphabeta.rs"

[[bin]]
name = "aux_witness"
path = "src/bin/aux_witness.rs"

[[bin]]
name = "save_sp1_groth16_bin"
path = "src/bin/save_sp1_groth16_bin.rs"

[[bin]]
name = "save_plonk_vk_json"
path = "src/bin/save_plonk_vk_json.rs"

[dependencies]
ark-ff = "0.4.2"
ark-ff-macros = "0.4.2"
ark-bn254 = "0.4.0"
ark-std = "0.4.0"
ark-ec = "0.4.2"
ark-poly = "0.4.0"
ark-serialize = "0.4.2"
ark-groth16 = "0.4.0"
ark-snark = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_tuple = "1.1"
num-bigint = "0.4"
num-traits = "0.2"
hex = "0.4"
sp1-sdk = { version = "6.0.1", optional = true }
thiserror = "1.0"

# WebAssembly-specific output (for wasm-pack)
# [target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.4"
tsify = "0.5"

[features]
wasm = ["wasm-bindgen", "serde-wasm-bindgen", "tsify"]
sp1-bin = ["sp1-sdk"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sp1-verifier = "6.0.1"

# Conditional dependencies for Wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
serde-wasm-bindgen = { version = "0.4", optional = true }
tsify = { version = "0.5", optional = true }