//! Extraction and cross-validation of risc0's recursion control-id constants.
//!
//! # Canonical version
//!
//! This module targets **risc0 `v3.0.6`** (the zkvm/toolchain release tag:
//! <https://github.com/risc0/risc0/releases/tag/v3.0.6>). That's the single
//! version number to think of as "the risc0 version" here, the same role
//! `6.1.0` plays for SP1 elsewhere in this crate. Every other version number
//! below belongs to a component that risc0 ships *as part of* that release
//! but numbers independently (risc0's crates are not version-locked to the
//! toolchain release number the way SP1's are) - each is called out with why
//! it looks lower/different rather than left unexplained:
//!
//! - `risc0-circuit-recursion = "4.0.5"` (pinned in `Cargo.toml`) - the crate
//!   that ships `ALLOWED_CONTROL_ROOT`/`BN254_IDENTITY_CONTROL_ID`. Its own
//!   version counter (`4.0.5`) is unrelated to and happens to be higher than
//!   the `v3.0.6` toolchain release it's part of; the two are correlated
//!   through `risc0-zkvm 3.0.6`'s dependency graph, not the number itself
//!   (confirmed by `cargo build` pulling `risc0-circuit-recursion 4.0.5`
//!   transitively when `risc0-zkvm = "3.0.6"` - see `example-generators/risc0/`).
//! - `risc0-groth16 = "3.0.5"` (pinned in `example-generators/risc0/host/Cargo.toml`) -
//!   the crate that decodes/verifies the Groth16 seal and embeds the fixed
//!   wrapper verifying key. Lower patch number than the toolchain release
//!   for the same reason: independent per-crate versioning within the same
//!   risc0 monorepo release.
//! - risc0-ethereum tag `v3.0.1` - **not a dependency of anything** and not
//!   version-correlated with `v3.0.6` at all (separate repo: the Solidity
//!   verifier contracts, with its own release cadence). Used exactly once,
//!   below, as an independent sanity check that the Rust-side constants
//!   match what an on-chain verifier expects. If it's ever revisited, treat
//!   it as "whatever risc0-ethereum tag was current at the time", not as a
//!   pin that needs to track `v3.0.6`.
//!
//! Both of the two independent checks performed here agree on the resulting
//! `pi1/pi2/pi5` values: this module's derivation cross-validated against
//! risc0-ethereum's Solidity source (below), and separately, a real risc0
//! proof generated and self-verified end-to-end against risc0 `v3.0.6`
//! (`example-generators/risc0/`, whose `host/src/main.rs` computes the same values via
//! logic transcribed from `risc0-groth16` and confirms them by independently
//! re-running Groth16 verification against the real seal).
//!
//! # Derivation
//!
//! risc0's Groth16-wrapped receipts expose the same class of "which recursion
//! programs do we trust" value that SP1 exposes as `vk_root` (see
//! `sp1_vk_root.ts` / `save_sp1_vk_root.rs`), but risc0 splits it across
//! three of the five Groth16 public inputs instead of one, and puts them in
//! a different position.
//!
//! Ground truth for both the constants and their layout is
//! `RiscZeroGroth16Verifier.sol` in risc0-ethereum:
//! <https://github.com/risc0/risc0-ethereum/blob/v3.0.1/contracts/src/groth16/RiscZeroGroth16Verifier.sol>
//!
//! ```solidity
//! function splitDigest(bytes32 digest) internal pure returns (bytes16, bytes16) {
//!     uint256 reversed = reverseByteOrderUint256(uint256(digest));
//!     return (bytes16(uint128(reversed)), bytes16(uint128(reversed >> 128)));
//! }
//! // ...
//! (bytes16 claim0, bytes16 claim1) = splitDigest(claimDigest);
//! [
//!     uint256(uint128(CONTROL_ROOT_0)),
//!     uint256(uint128(CONTROL_ROOT_1)),
//!     uint256(uint128(claim0)),
//!     uint256(uint128(claim1)),
//!     uint256(BN254_CONTROL_ID)
//! ]
//! ```
//!
//! and `ControlID.sol` (auto-generated by `cargo xtask bootstrap-groth16`)
//! for the literal constant values:
//! <https://github.com/risc0/risc0-ethereum/blob/v3.0.1/contracts/src/groth16/ControlID.sol>
//!
//! ```solidity
//! bytes32 public constant CONTROL_ROOT = hex"a54dc85ac99f851c92d7c96d7318af41dbe7c0194edfcc37eb4d422a998c1f56";
//! // NOTE: This has the opposite byte order to the value in the risc0 repository.
//! bytes32 public constant BN254_CONTROL_ID = hex"04446e66d300eb7fb45c9726bb53c793dda407a62e9601618bb43c5c14657ac0";
//! ```
//!
//! Cross-checking those literals against the Rust-side constants (see the
//! `tests` module below, run with `cargo test -p proof-conversion-utils
//! risc0_control_id`) establishes two byte-order facts empirically rather
//! than by assumption:
//!
//! 1. `ControlID.sol::CONTROL_ROOT` is byte-identical to
//!    `risc0_circuit_recursion::control_id::ALLOWED_CONTROL_ROOT.as_bytes()`
//!    — no reversal between the Rust constant and the unsplit Solidity
//!    constant.
//! 2. `ControlID.sol::BN254_CONTROL_ID` is the exact reverse-byte-order of
//!    `risc0_circuit_recursion::control_id::BN254_IDENTITY_CONTROL_ID.as_bytes()`
//!    — confirming the Solidity comment above literally, not just as a note.
//!
//! Consequently, for a Groth16 receipt's five public inputs `pi1..pi5`
//! (1-indexed, matching this repo's `O1jsProof` naming):
//!
//! - `pi1, pi2` = `split_digest(ALLOWED_CONTROL_ROOT.as_bytes())` = (low, high)
//! - `pi3, pi4` = the claim digest (image_id + journal digest) split the same
//!   way — this is receipt-specific data, analogous to SP1's `pi0`/`pi1`, and
//!   is *not* a constant to pin here.
//! - `pi5` = `reverse_bytes(BN254_IDENTITY_CONTROL_ID.as_bytes())` interpreted
//!   as a big-endian BN254 scalar field element, used directly (no split).
//!
//! `split_digest`'s low/high assignment (as opposed to high/low) is verified
//! independently in `split_digest_matches_solidity_convention` below using a
//! hand-computed vector, since Solidity does not expose `CONTROL_ROOT_0`/
//! `CONTROL_ROOT_1` as standalone constants to compare against directly (the
//! split only happens inside `_verifyIntegrity` at verification time).

use risc0_circuit_recursion::control_id::{ALLOWED_CONTROL_ROOT, BN254_IDENTITY_CONTROL_ID};

/// Byte-reverses a 32-byte digest, mirroring Solidity's `reverseByteOrderUint256`.
pub fn reverse_bytes(bytes: &[u8; 32]) -> [u8; 32] {
    let mut out = *bytes;
    out.reverse();
    out
}

/// Mirrors `RiscZeroGroth16Verifier.sol::splitDigest`: byte-reverses the
/// digest, then splits the resulting 256-bit big-endian value into its low
/// 128 bits and high 128 bits. Returns `(low, high)` = `(CONTROL_ROOT_0,
/// CONTROL_ROOT_1)` / `(claim0, claim1)`.
pub fn split_digest(bytes: &[u8; 32]) -> ([u8; 16], [u8; 16]) {
    let reversed = reverse_bytes(bytes);
    let mut high = [0u8; 16];
    let mut low = [0u8; 16];
    high.copy_from_slice(&reversed[0..16]);
    low.copy_from_slice(&reversed[16..32]);
    (low, high)
}

/// The risc0 recursion control root, as it appears verbatim in
/// `ControlID.sol::CONTROL_ROOT` (see module docs for the cross-check).
pub fn allowed_control_root_bytes() -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(ALLOWED_CONTROL_ROOT.as_bytes());
    out
}

/// The BN254 identity control ID, in the byte order Solidity actually uses
/// as a Groth16 public input (i.e. already reversed relative to the Rust
/// constant — see module docs).
pub fn bn254_control_id_bytes() -> [u8; 32] {
    let mut raw = [0u8; 32];
    raw.copy_from_slice(BN254_IDENTITY_CONTROL_ID.as_bytes());
    reverse_bytes(&raw)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Ground truth pulled verbatim from risc0-ethereum tag v3.0.1:
    /// https://github.com/risc0/risc0-ethereum/blob/v3.0.1/contracts/src/groth16/ControlID.sol
    const SOLIDITY_CONTROL_ROOT_V3_0_1: &str =
        "a54dc85ac99f851c92d7c96d7318af41dbe7c0194edfcc37eb4d422a998c1f56";
    const SOLIDITY_BN254_CONTROL_ID_V3_0_1: &str =
        "04446e66d300eb7fb45c9726bb53c793dda407a62e9601618bb43c5c14657ac0";

    #[test]
    fn allowed_control_root_matches_solidity_control_id_sol() {
        let expected = hex::decode(SOLIDITY_CONTROL_ROOT_V3_0_1).unwrap();
        assert_eq!(
            allowed_control_root_bytes().to_vec(),
            expected,
            "risc0_circuit_recursion::ALLOWED_CONTROL_ROOT no longer matches \
             ControlID.sol::CONTROL_ROOT from risc0-ethereum v3.0.1 - either \
             the pinned risc0-circuit-recursion version drifted from v3.0.1, \
             or the byte-order assumption documented in this module is wrong."
        );
    }

    #[test]
    fn bn254_control_id_reversed_matches_solidity_control_id_sol() {
        let expected = hex::decode(SOLIDITY_BN254_CONTROL_ID_V3_0_1).unwrap();
        assert_eq!(
            bn254_control_id_bytes().to_vec(),
            expected,
            "reverse_bytes(BN254_IDENTITY_CONTROL_ID) no longer matches \
             ControlID.sol::BN254_CONTROL_ID from risc0-ethereum v3.0.1."
        );
    }

    /// Confirms `split_digest`'s low/high assignment independent of the real
    /// constants, using a digest where each byte is distinct so a
    /// transposition bug (low/high swapped, or reversal applied to the
    /// wrong half) would be caught.
    #[test]
    fn split_digest_matches_solidity_convention() {
        // digest = 00 01 02 .. 1f (big-endian bytes32, as Solidity would see it)
        let mut digest = [0u8; 32];
        for (i, b) in digest.iter_mut().enumerate() {
            *b = i as u8;
        }

        // reverseByteOrderUint256: reversed = 1f 1e .. 00
        // uint128(reversed)        = low 128 bits = last 16 bytes of `reversed` = 0f 0e .. 00
        // uint128(reversed >> 128) = high 128 bits = first 16 bytes of `reversed` = 1f 1e .. 10
        let expected_low: [u8; 16] = [
            0x0f, 0x0e, 0x0d, 0x0c, 0x0b, 0x0a, 0x09, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02,
            0x01, 0x00,
        ];
        let expected_high: [u8; 16] = [
            0x1f, 0x1e, 0x1d, 0x1c, 0x1b, 0x1a, 0x19, 0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12,
            0x11, 0x10,
        ];

        let (low, high) = split_digest(&digest);
        assert_eq!(low, expected_low, "low half (CONTROL_ROOT_0) mismatch");
        assert_eq!(high, expected_high, "high half (CONTROL_ROOT_1) mismatch");
    }
}
